# версия docker-compose
version: '3.8'

# имя директории для хранения данных
volumes:
  postgres_data:
  static_volume:
  media_volume:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:12.4
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  app:
    build: .
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    # "зависит от",
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.10
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app